using Dx.Domain.Analyzers.Infrastructure.Generated;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

using Moq;

using Xunit;

using Assert = Xunit.Assert;

namespace Dx.Domain.Analyzers.Tests.UnitTests
{
    public class GeneratedCodeDetectorTests
    {
        [Fact]
        public void Symbol_With_GeneratedCodeAttribute_IsGenerated_Returns_True()
        {
            var code = """
                using System.CodeDom.Compiler;

                [GeneratedCode("Tool", "1.0")]
                public class GeneratedClass
                {
                }
                """;

            var symbol = GetTypeSymbol(code, "GeneratedClass");
            var detector = CreateDetector(null);

            Assert.True(detector.IsGenerated(symbol));
        }

        [Fact]
        public void Symbol_With_CompilerGeneratedAttribute_IsGenerated_Returns_True()
        {
            var code = """
                using System.Runtime.CompilerServices;

                [CompilerGenerated]
                public class CompilerGeneratedClass
                {
                }
                """;

            var symbol = GetTypeSymbol(code, "CompilerGeneratedClass");
            var detector = CreateDetector(null);

            Assert.True(detector.IsGenerated(symbol));
        }

        [Fact]
        public void Symbol_In_Configured_Namespace_Marker_IsGenerated_Returns_True()
        {
            var code = """
                namespace GeneratedCode.Models
                {
                    public class Model
                    {
                    }
                }
                """;

            var symbol = GetTypeSymbol(code, "GeneratedCode.Models.Model");
            var detector = CreateDetector("GeneratedCode");

            Assert.True(detector.IsGenerated(symbol));
        }

        [Fact]
        public void Regular_User_Code_IsGenerated_Returns_False()
        {
            var code = """
                namespace MyApp.Domain
                {
                    public class UserClass
                    {
                    }
                }
                """;

            var symbol = GetTypeSymbol(code, "MyApp.Domain.UserClass");
            var detector = CreateDetector(null);

            Assert.False(detector.IsGenerated(symbol));
        }

        [Fact]
        public void Multiple_Namespace_Markers_Are_Supported()
        {
            var code1 = """
                namespace GeneratedCode.Models
                {
                    public class Model1 {}
                }
                """;

            var code2 = """
                namespace AutoGenerated.Services
                {
                    public class Service1 {}
                }
                """;

            var compilation = CSharpCompilation.Create(
                "Test",
                new[] {
                    CSharpSyntaxTree.ParseText(code1),
                    CSharpSyntaxTree.ParseText(code2)
                },
                new[] {
                    MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
                });

            var detector = CreateDetector("GeneratedCode;AutoGenerated");

            var symbol1 = compilation.GetTypeByMetadataName("GeneratedCode.Models.Model1");
            var symbol2 = compilation.GetTypeByMetadataName("AutoGenerated.Services.Service1");

            Assert.True(detector.IsGenerated(symbol1!));
            Assert.True(detector.IsGenerated(symbol2!));
        }

        [Fact]
        public void Namespace_Prefix_Matching_Works()
        {
            var code = """
                namespace GeneratedCode.Models.SubNamespace
                {
                    public class DeepModel {}
                }
                """;

            var symbol = GetTypeSymbol(code, "GeneratedCode.Models.SubNamespace.DeepModel");
            var detector = CreateDetector("GeneratedCode");

            Assert.True(detector.IsGenerated(symbol));
        }

        [Fact]
        public void No_Config_And_No_Attributes_Returns_False()
        {
            var code = """
                namespace MyApp
                {
                    public class RegularClass {}
                }
                """;

            var symbol = GetTypeSymbol(code, "MyApp.RegularClass");
            var detector = CreateDetector(null);

            Assert.False(detector.IsGenerated(symbol));
        }

        [Fact]
        public void Whitespace_In_Namespace_Markers_Is_Handled()
        {
            var code = """
                namespace GeneratedCode.Models
                {
                    public class Model {}
                }
                """;

            var symbol = GetTypeSymbol(code, "GeneratedCode.Models.Model");
            var detector = CreateDetector(" GeneratedCode ; AutoGen ");

            Assert.True(detector.IsGenerated(symbol));
        }

        [Fact]
        public void Empty_Namespace_Markers_Are_Ignored()
        {
            var code = """
                namespace MyApp
                {
                    public class RegularClass {}
                }
                """;

            var symbol = GetTypeSymbol(code, "MyApp.RegularClass");
            var detector = CreateDetector(";;GeneratedCode;;");

            Assert.False(detector.IsGenerated(symbol));
        }

        private static IGeneratedCodeDetector CreateDetector(string? namespaceMarkers)
        {
            var mockConfig = new Mock<AnalyzerConfigOptionsProvider>();
            var mockOptions = new Mock<AnalyzerConfigOptions>();

            if (namespaceMarkers != null)
            {
                mockOptions.Setup(o => o.TryGetValue("dx_generated_markers", out It.Ref<string>.IsAny))
                    .Returns((string key, out string value) =>
                    {
                        value = namespaceMarkers;
                        return true;
                    });
            }

            mockConfig.Setup(c => c.GlobalOptions).Returns(mockOptions.Object);
            return new GeneratedCodeDetector(mockConfig.Object);
        }

        private static ITypeSymbol GetTypeSymbol(string code, string fullyQualifiedName)
        {
            var compilation = CSharpCompilation.Create(
                "Test",
                new[] { CSharpSyntaxTree.ParseText(code) },
                new[] {
                    MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(System.CodeDom.Compiler.GeneratedCodeAttribute).Assembly.Location)
                });

            var symbol = compilation.GetTypeByMetadataName(fullyQualifiedName);
            Assert.NotNull(symbol);
            return symbol!;
        }
    }
}
