<Project Label="Dx.Policy.Enforcement">
  <Target Name="DxEnforceForbiddenPolicies" BeforeTargets="PrepareForBuild">
    <ItemGroup>
      <_DxViolation Include="@(DxForbiddenProperty)"
                    Condition="'$($(DxForbiddenProperty.Identity))' != ''" />
    </ItemGroup>

    <Error Condition="'@(_DxViolation)' != ''"
           Code="DXB001"
           File="$(MSBuildProjectFullPath)"
           Text="[Dx Architecture] Policy Violation: Property '%(_DxViolation.Identity)' is managed by the Kernel. Local project overrides are forbidden." />
  </Target>
</Project>
