<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <DxIsLibrary>true</DxIsLibrary>

    <RootNamespace>Dx.Domain</RootNamespace>
    <AssemblyName>Dx.Domain.Kernel</AssemblyName>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Description>
      The Dx.Domain.Kernel package provides a small, opinionated kernel for invariants, results, and errors.
      It exists to make incorrect domain modeling impossible to ignore, not to act as a convenience library.
    </Description>
    <PackageTags>dx;ddd;functional;result-pattern;invariants;errors</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Dx.Domain.Values" />
    <InternalsVisibleTo Include="Dx.Domain.Analyzers" />
    <InternalsVisibleTo Include="Dx.Domain.Generators" />
    <InternalsVisibleTo Include="Dx.Domain.Persistence" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dx.Domain.Annotations\Dx.Domain.Annotations.csproj" />
    <ProjectReference Include="..\Dx.Domain.Primitives\Dx.Domain.Primitives.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dx.Domain.Analyzers\Dx.Domain.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <None Update="../../CHANGELOG.md" Link="docs/CHANGELOG.md" />
    <None Update="../../README.md" Link="docs/README.md" />
    <None Update="../../LICENSE" Link="docs/LICENSE" />
  </ItemGroup>

</Project>
