<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <DxIsLibrary>true</DxIsLibrary>

    <RootNamespace>Dx</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Description>
      The Dx.Domain package provides a powerful, attribute-based system for declaring and discovering metadata.
      The core kernel focuses on strictly typed results, errors, and invariants.
    </Description>
    <PackageTags>dx;ddd;functional;result-pattern;metadata</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Dx.Domain.Values" />
    <InternalsVisibleTo Include="Dx.Domain.Analyzers" />
    <InternalsVisibleTo Include="Dx.Domain.Generators" />
    <InternalsVisibleTo Include="Dx.Domain.Persistence" />
  </ItemGroup>

  <ItemGroup>
    <None Update="../../CHANGELOG.md" Link="docs/CHANGELOG.md" />
    <None Update="../../README.md" Link="docs/README.md" />
    <None Update="../../LICENSE" Link="docs/LICENSE" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dx.Domain.Abstractions\Dx.Domain.Abstractions.csproj" />
  </ItemGroup>

</Project>
