<!-- Dx.Domain.Abstractions Project File -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>10</LangVersion>

    <AssemblyName>Dx.Domain.Abstractions</AssemblyName>
    <RootNamespace>Dx.Domain</RootNamespace>

    <IsAbstractionsProject>true</IsAbstractionsProject>

    <IsDomainProject>false</IsDomainProject>
    <IsToolingProject>false</IsToolingProject>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Label="Dx.Abstractions.Quality">
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" Version="10.0.1" />
  </ItemGroup>

</Project>
