<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Dx.Identity">
    <DxIsLibrary>true</DxIsLibrary>
    <DxLayer>Annotations</DxLayer>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <Description>Semantic vocabulary for Dx.Domain (pure metadata: markers, attributes, canon).</Description>
    <PackageTags>dx;ddd;annotations;attributes;domain-model</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="DxLayer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dx.Domain.Analyzers\Dx.Domain.Analyzers.csproj"
                  OutputItemType="Analyzer"
                  ReferenceOutputAssembly="false"
                  PrivateAssets="all"
                  DxIncludeAsAnalyzer="true" />
  </ItemGroup>

  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
