<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Dx.Identity">
    <DxIsLibrary>true</DxIsLibrary>
    <DxLayer>Primitives</DxLayer>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Description>The Dx.Domain.Primitives package provides low-level primitives for domain modeling and observability.</Description>
    <PackageTags>dx;ddd;primitives;user-id;fact-id;correlation-id;observability</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="DxLayer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dx.Domain.Annotations\Dx.Domain.Annotations.csproj" />
    <ProjectReference Include="..\Dx.Domain.Analyzers\Dx.Domain.Analyzers.csproj"
                  OutputItemType="Analyzer"
                  ReferenceOutputAssembly="false"
                  PrivateAssets="all"
                  DxIncludeAsAnalyzer="true" />
  </ItemGroup>

  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
